
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#f6f9fc',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
  },
  backText: {
    fontSize: 16,
    color: '#635BFF',
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginLeft: 10,
    color: '#1e293b',
    marginTop: 50
  },
  formCard: {
    width: "100%",
    backgroundColor: '#fff',
    padding: 22,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardSection: { marginBottom: 25 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: 10,
  },
  sheetButton: {
    backgroundColor: "#f1f5f9",
    borderRadius: 10,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    alignItems: "center",
  },
  sheetButtonDisabled: {
    backgroundColor: "#e2e8f0",
    opacity: 0.6,
  },
  sheetButtonText: {
    color: "#1e293b",
    fontSize: 16,
    fontWeight: "600",
  },
  message: {
    marginTop: 15,
    padding: 12,
    borderRadius: 8,
    fontSize: 14,
    textAlign: 'center',
  },
  error: {
    backgroundColor: '#ffe2e6',
    color: '#b4001e',
    borderColor: '#ffb3c0',
    borderWidth: 1,
  },
  info: {
    backgroundColor: '#e0f2fe',
    color: '#0369a1',
    borderColor: '#bae6fd',
    borderWidth: 1,
  },
  warningText: {
    marginTop: 10,
    padding: 10,
    backgroundColor: '#fff3cd',
    color: '#856404',
    borderRadius: 8,
    textAlign: 'center',
    fontSize: 14,
  },
  securityInfo: {
    marginTop: 25,
    padding: 15,
    alignItems: 'center',
  },
  securityText: {
    color: '#64748b',
    fontSize: 12,
    textAlign: 'center',
  },
  successContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#f6f9fc",
  },
  successCard: {
    backgroundColor: "#fff",
    padding: 30,
    borderRadius: 14,
    alignItems: "center",
    width: "100%",
    maxWidth: 300,
    shadowColor: "#000",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  successEmoji: { fontSize: 50, marginBottom: 10 },
  successTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#2e7d32",
    marginBottom: 8,
  },
  successText: {
    color: "#475569",
    fontSize: 15,
    textAlign: "center",
    marginBottom: 20,
  },
  redirectText: {
    color: "#64748b",
    fontSize: 12,
    marginTop: 5,
  },
  transparentCard: {
    backgroundColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
    borderWidth: 0,
    marginTop: 5,
    alignSelf: "center",
  },
  logo: {
    width: 200,
    height: 100,
    marginBottom: 30,
    marginTop: 5,
  },
  largeLogo: {
    width: 300 * 0.7,
    height: 150 * 0.7,
    marginBottom: 30,
  },
  card: {
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
});