import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#f8fafc',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#666',
  },
  filtersContainer: {
    gap: 12,
    marginBottom: 16,
  },
  dateToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    alignSelf: 'flex-start',
  },
  dateToggleText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
  },
  dateInputsContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  dateInputGroup: {
    flex: 1,
    gap: 4,
  },
  dateLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#374151',
  },
  dateInput: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 6,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  statsGrid: {
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  statContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  statTextContainer: {
    flex: 1,
  },
  statLabel: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 4,
  },
  statDescription: {
    fontSize: 12,
    color: '#9ca3af',
  },
  chartsContainer: {
    gap: 20,
    marginBottom: 24,
  },
  chartCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  yearSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  yearSelectorLabel: {
    fontSize: 14,
    color: '#6b7280',
  },
  yearSelect: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#f3f4f6',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  yearSelectText: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  barChartContainer: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingVertical: 8,
  },
  legendContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 16,
    gap: 12,
    paddingHorizontal: 8,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#f8fafc',
    borderRadius: 6,
  },
  legendColor: {
    width: 12,
    height: 12,
    borderRadius: 2,
  },
  legendText: {
    fontSize: 12,
    color: '#374151',
    fontWeight: '500',
  },
  noDataContainer: {
    height: 220,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderStyle: 'dashed',
  },
  noDataText: {
    fontSize: 16,
    color: '#9ca3af',
    textAlign: 'center',
  },
  additionalStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
  },
  miniStatCard: {
    flex: 1,
    minWidth: (Dimensions.get('window').width - 64) / 2 - 6,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  miniStatValue: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  miniStatLabel: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
  },
  // Agregar estos estilos a tu styles object
quickDateContainer: {
  marginTop: 12,
},
quickDateLabel: {
  fontSize: 14,
  fontWeight: '500',
  color: '#374151',
  marginBottom: 8,
},
quickDateButtons: {
  flexDirection: 'row',
  gap: 8,
},
quickDateButton: {
  backgroundColor: '#f3f4f6',
  paddingHorizontal: 12,
  paddingVertical: 6,
  borderRadius: 6,
  borderWidth: 1,
  borderColor: '#d1d5db',
},
quickDateButtonText: {
  fontSize: 12,
  color: '#374151',
  fontWeight: '500',
},
currentRange: {
  marginTop: 12,
  padding: 8,
  backgroundColor: '#f0f9ff',
  borderRadius: 6,
  borderLeftWidth: 4,
  borderLeftColor: '#0ea5e9',
},
currentRangeText: {
  fontSize: 12,
  color: '#0369a1',
  fontWeight: '500',
},
dateSectionTitle: {
  fontSize: 16,
  fontWeight: '600',
  color: '#1f2937',
  marginBottom: 16,
},
dateSelectionContainer: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  gap: 12,
},
dateButton: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#f9fafb',
  borderWidth: 1,
  borderColor: '#d1d5db',
  borderRadius: 8,
  paddingHorizontal: 12,
  paddingVertical: 10,
  gap: 8,
},
dateButtonText: {
  fontSize: 14,
  color: '#1f2937',
},
dateButtonTextDisabled: {
  color: '#9ca3af',
},
clearButton: {
  marginTop: 12,
  padding: 10,
  backgroundColor: '#fef2f2',
  borderRadius: 6,
  borderWidth: 1,
  borderColor: '#fecaca',
  alignItems: 'center',
},
clearButtonText: {
  fontSize: 12,
  color: '#dc2626',
  fontWeight: '500',
},
currentRangeDisplay: {
  marginTop: 12,
  padding: 12,
  backgroundColor: '#f0f9ff',
  borderRadius: 8,
  borderLeftWidth: 4,
  borderLeftColor: '#0ea5e9',
},
currentRangeLabel: {
  fontSize: 12,
  color: '#0369a1',
  fontWeight: '600',
  marginBottom: 4,
},
currentRangeText: {
  fontSize: 14,
  color: '#1e40af',
  fontWeight: '500',
},
});